version: '3'
services:
  plugin_store:
    build: .
    container_name: "${DEPLOYMENT_NAME}"
    environment:
        - DB_PATH
        - ANNOUNCEMENT_WEBHOOK
        - SUBMIT_AUTH_KEY
        - B2_APP_KEY_ID
        - B2_APP_KEY
        - B2_BUCKET_ID
    volumes:
        - ~/database:/db
    networks:
        - plugins-network
    restart: unless-stopped

  redis_db:
    image: redis:3.2.8
    restart: unless-stopped
    ports:
      - 6379:6379
    environment:
      - REDIS_PORT=6379
    

networks:
  plugins-network:
    external: true
    driver: bridge
    name: caddy__bridge
