[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "decky-plugin-store"
version = "0.1.0"
description = "Plugin Store backend for Decky"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "decky_plugin_store"}]

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = "^3.7.4.post0"
aiohttp-cors = "^0.7.0"
aiosqlite = "^0.17.0"
# discord-py = "^1.7.3"
discord-webhook = {version = "^0.17.0", extras = ["async"]}
sqlalchemy = "^1.4.41"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
pytest-aiohttp = "^1.0.4"
pytest-env = "^0.6.2"
pytest-lazy-fixture = "^0.6.3"
pytest-mock = "^3.8.2"

[tool.black]
line-length = 120
target-version = ['py39', 'py310', 'py311']
include = '\.pyi?$'
exclude = '''
(
    /(
        \.eggs
      | \.git
      | \.hg
      | \.mypy_cache
      | \.tox
      | \.venv
      | _build
      | buck-out
      | build
      | dist
    )/
)
'''

[tool.isort]
line_length = 120
order_by_type = false
profile = "black"
src_paths = ["plugin_store"]
